name: build

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
      target:
        default: "base"
        type: string
      labels:
        default: ""
        type: string
      cache:
        default: false
        type: boolean
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      CACHE_FROM: type=local,src=/tmp/buildx
      CACHE_TO: type=local,dest=/tmp/buildx
    steps:
      - name: Setup cache
        if: ${{ inputs.cache }}
        run: |
          echo "CACHE_FROM=type=gha" >> $GITHUB_ENV
          echo "CACHE_TO=type=gha,mode=max" >> $GITHUB_ENV
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ inputs.tags }}
          target: ${{ inputs.target }}
          cache-from: ${{ env.CACHE_FROM }}
          cache-to: ${{ env.CACHE_TO }}
      - name: Generate Output
        run: echo "hello=world" >> $GITHUB_OUTPUT